const use_opt = [
    { value:'',     text:'필수 선택' },
    { value:'1',    text:'[학술] 초록' },
    { value:'2',    text:'[학술] 사례연구' },
    { value:'3',    text:'[학술] 연구비 신청서' },
    { value:'4',    text:'[학술] 출판 원고' },
    { value:'5',    text:'[학술] 컨퍼런스 발표자료' },
    { value:'6',    text:'[학술] 피어 리뷰 코멘트' },
    { value:'7',    text:'[학술] 프레젠테이션/포스터' },
    { value:'8',    text:'[학술] 학술논문/저널 아티클' },
    { value:'9',    text:'[학술] 피어리뷰 코멘트에 대한 답변' },
    { value:'10',   text:'[학술] 학위 논문' },
    { value:'11',   text:'[학술] 기타 학술 관련 문서' },
    { value:'12',   text:'[학술 문서 이외] 연례 보고서' },
    { value:'13',   text:'[학술 문서 이외] 편지/이메일' },
    { value:'14',   text:'[학술 문서 이외] 마케팅/홍보자료' },
    { value:'15',   text:'[학술 문서 이외] 프레젠테이션/연설문' },
    { value:'16',   text:'[학술 문서 이외] 웹사이트' },
    { value:'17',   text:'[학술 문서 이외] 기타 (학술문서 외)' },
];
const branch_opt = [
    { value:"",  text:'필수 선택' },
    { value:"1",  text:'Arts, Media, and Communication' },
    { value:"2",  text:'Biochemistry, Genetics, and Molecular Biology' },
    { value:"3",  text:'Business and Finance' },
    { value:"4",  text:'Chemistry' },
    { value:"5",  text:'Computer Science and Mathematics' },
    { value:"6",  text:'Earth, Atmospheric, and Planetary Science' },
    { value:"7",  text:'Economics and Statistics' },
    { value:"8",  text:'Education' },
    { value:"9",  text:'Engineering and Technology' },
    { value:"10", text:'Environmental Science, Energy, and Sustainability' },
    { value:"11", text:'History, Political Science, and Philosophy' },
    { value:"12", text:'Literature and Linguistics' },
    { value:"13", text:'Materials Science' },
    { value:"14", text:'Medicine' },
    { value:"15", text:'Neuroscience and Neurology' },
    { value:"16", text:'Pharmaceutical Sciences' },
    { value:"17", text:'Physics' },
    { value:"18", text:'Plant and Animal Science' },
    { value:"19", text:'Psychology and Psychosocial Healthcare' },
    { value:"20", text:'Sociology, Anthropology, and Organizational Behavior' },
];
const editor_opt = [
    [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Art history 미술사" },
        { value:"2",    text: "Autobiography/Biography 자서전/전기" },
        { value:"3",    text: "Basic English learning content 기초 영어 학습 컨텐츠" },
        { value:"4",    text: "Communication studies 커뮤니케이션학" },
        { value:"5",    text: "Design and aesthetics 디자인 및 미학" },
        { value:"6",    text: "Dialogue 대화" },
        { value:"7",    text: "Fine arts 순수미술" },
        { value:"8",    text: "Individual/Organization profile 개인/기관 프로필" },
        { value:"9",    text: "Instruction manual/Guidelines 사용안내서/가이드라인" },
        { value:"10",   text: "Media and journalism 미디어 및 저널리즘" },
        { value:"11",   text: "Music 음악" },
        { value:"12",   text: "News/Magazine reports or articles 뉴스/매거진리포트 또는 기사" },
        { value:"13",   text: "Opinion, non-academic essay, or commentary 여론, 비학술논문 또는 논평" },
        { value:"14",   text: "Other - Arts, media, and communication 기타 - 예술, 미디어 및 커뮤니케이션" },
        { value:"15",   text: "Performing arts 공연예술" },
        { value:"16",   text: "Personal communication 퍼스널 커뮤니케이션" },
        { value:"17",   text: "Project/Program description 프로젝트/프로그램 서술" },
        { value:"18",   text: "Promotional content 프로모션 컨텐츠" },
        { value:"19",   text: "Recommendation letter 추천서" },
        { value:"20",   text: "Resumes 이력서" },
        { value:"21",   text: "School/University/Job application 학교/취업지원서" },
        { value:"22",   text: "Sports and recreation 스포츠 및 레크리에이션" },
        { value:"23",   text: "Tourism studies 관광학" },
        { value:"24",   text: "TV and film TV 및 영화" },
        { value:"25",   text: "Visual and fine arts 시각 및 순수미술" },
        { value:"26",   text: "Visual arts 시각예술" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1", text: "Aging 노화" },
        { value:"2", text: "Biochemistry 생화학" },
        { value:"3", text: "Biofuels 바이오연료" },
        { value:"4", text: "Bioinformatics and computational biology 생물정보학 및 전산생물학" },
        { value:"5", text: "Biomaterials 바이오소재" },
        { value:"6", text: "Biophysics 생물물리학" },
        { value:"7", text: "Biostatistics 생물통계학" },
        { value:"8", text: "Cell biology 세포생물학" },
        { value:"9", text: "Embryology 발생학" },
        { value:"10",    text: "Enzymology and bioenergetics 효소 및 생물에너지학" },
        { value:"11",    text: "Evolutionary and developmental biology 진화 및 발생생물학" },
        { value:"12",    text: "Evolutionary genetics 진화유전학" },
        { value:"13",    text: "Food science 식품과학" },
        { value:"14",    text: "Forensic science 범죄과학" },
        { value:"15",    text: "Genetics and genomics 유전 및 유전체학" },
        { value:"16",    text: "Immunology 면역학" },
        { value:"17",    text: "Medical laboratory technology 의료실험실 기술" },
        { value:"18",    text: "Microbial biotechnology 미생물 생명공학" },
        { value:"19",    text: "Microbiology 미생물학" },
        { value:"20",    text: "Molecular biology 분자생물학" },
        { value:"21",    text: "Molecular medicine 분자의학" },
        { value:"22",    text: "Molecular oncology 분자종양학" },
        { value:"23",    text: "Mutagenesis 돌연변이 생성학" },
        { value:"24",    text: "Nanobiotechnology 나노바이오테크놀로지" },
        { value:"25",    text: "Neuroscience - Cellular and molecular 신경과학 - 세포 및 분자" },
        { value:"26",    text: "Oncogenetics 종양유전학" },
        { value:"27",    text: "Other - Biochemistry, genetics, and molecular biology 기타 - 생화학, 유전학 및 분자생물학" },
        { value:"28",    text: "Physiology 생리학" },
        { value:"29",    text: "Population genetics 집단유전학" },
        { value:"30",    text: "Reproductive biology 생식생물학" },
        { value:"31",    text: "Stem cell engineering 줄기세포공학" },
        { value:"32",    text: "Structural biology 구조생물학" },
        { value:"33",    text: "Systems biology 시스템생물학" },
        { value:"34",    text: "Transplantation immunology 이식 면역학" },
        { value:"35",    text: "Virology 바이러스학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1", text: "Accounting, auditing, insurance, and tax 회계학, 회계감사, 보험 및 세금" },
        { value:"2", text: "Annual reports, quarterly reports, and financial statements 연차보고서, 분기보고서 및 재무제표" },
        { value:"3", text: "Banking, finance, and risk management 은행, 금융 및 위험관리" },
        { value:"4", text: "Business analysis, financial analysis, and financial reports 비즈니스분석, 재무분석 및 재무보고서" },
        { value:"5", text: "Business management and administration 경영 및 관리" },
        { value:"6", text: "Consumer studies 소비자학 연구" },
        { value:"7", text: "Human resource management and industrial relations 인적자원관리 및 노무관리" },
        { value:"8", text: "Management consulting and case studies 경영컨설팅 및 사례연구" },
        { value:"9", text: "Manufacturing, production, and logistics 제조, 생산 및 물류" },
        { value:"10",    text: "Marketing and advertising 마케팅 및 광고학" },
        { value:"11",    text: "Other - Business and finance 기타 - 경영 및 금융학" },
        { value:"12",    text: "Strategic management, operations management, and planning 전략적 경영, 운영관리 및 기획" },
        { value:"13",    text: "Supply chain management  물류관리, 물류학" },
        { value:"14",    text: "Tourism, leisure, and hospitality management 관광, 레저 및 호텔경영" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1", text: "Analytical chemistry 분석화학" },
        { value:"2", text: "Applied chemistry 응용화학" },
        { value:"3", text: "Catalysis 촉매작용" },
        { value:"4", text: "Chemical engineering 화학공학" },
        { value:"5", text: "Colloid and surface chemistry 콜로이드 및 표면화학" },
        { value:"6", text: "Computational chemistry   컴퓨터 화학/계산화학" },
        { value:"7", text: "Electrochemistry 전기화학" },
        { value:"8", text: "Food chemistry 식품화학" },
        { value:"9", text: "Inorganic chemistry 무기화학" },
        { value:"10",    text: "Macromolecular and materials chemistry 고분자 및 재료화학" },
        { value:"11",    text: "Nanochemistry 나노화학" },
        { value:"12",    text: "Organic chemistry 유기화학" },
        { value:"13",    text: "Other - Chemistry 기타 - 화학" },
        { value:"14",    text: "Pharmaceutical and medicinal chemistry 의약품 및 의약화학" },
        { value:"15",    text: "Photochemistry 광화학" },
        { value:"16",    text: "Physical chemistry 물리화학" },
        { value:"17",    text: "Polymer chemistry 고분자화학" },
        { value:"18",    text: "Structural chemistry 구조화학" },
        { value:"19",    text: "Supramolecular chemistry 초분자화학" },
        { value:"20",    text: "Theoretical chemistry 이론화학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1", text: "Algebra and number theory 대수학 및 정수론" },
        { value:"2", text: "Applied mathematics 응용수학" },
        { value:"3", text: "Artificial intelligence 인공지능" },
        { value:"4", text: "Calculus 미적분학" },
        { value:"5", text: "Computer and mobile application software 컴퓨터 및 모바일 응용소프트웨어" },
        { value:"6", text: "Computer graphics and color spaces 컴퓨터 그래픽 및 색공간" },
        { value:"7", text: "Computer hardware and peripheral devices 컴퓨터 하드웨어 및 주변장치" },
        { value:"8", text: "Computer science 컴퓨터공학" },
        { value:"9", text: "Computer security and cryptography 컴퓨터 보안 및 암호해독" },
        { value:"10",    text: "Computer vision 컴퓨터 비전" },
        { value:"11",    text: "Database systems and data mining 데이터베이스 시스템 및 데이터마이닝" },
        { value:"12",    text: "Geometry and topology 기하학 및 지형학" },
        { value:"13",    text: "Human-Computer interaction 인간-컴퓨터 상호작용" },
        { value:"14",    text: "Image and video processing 이미지 및 영상처리" },
        { value:"15",    text: "Information systems 정보시스템" },
        { value:"16",    text: "Internet, web services, and cloud computing 인터넷, 웹서비스 및 클라우드 컴퓨팅" },
        { value:"17",    text: "Machine learning and pattern recognition 기계학습 및 패턴인식" },
        { value:"18",    text: "Mathematical modeling, scheduling, and optimization 수학적모델링, 스케쥴링 및 최적화" },
        { value:"19",    text: "Mathematics 수학" },
        { value:"20",    text: "Mobile computing 모바일 컴퓨팅" },
        { value:"21",    text: "Networks and communication protocols 네트워크 및 통신프로토콜" },
        { value:"22",    text: "Neural networks and fuzzy systems 신경망 및 퍼지시스템" },
        { value:"23",    text: "Operating systems and computer architecture 운영체제 및 컴퓨터구조" },
        { value:"24",    text: "Other - Computer science and mathematics 기타 - 컴퓨터공학 및 수학" },
        { value:"25",    text: "Parallel and distributed systems 병렬 및 분산시스템" },
        { value:"26",    text: "Programming, algorithms, and data structures 프로그래밍, 알고리즘 및 데이터구조" },
        { value:"27",    text: "Software engineering 소프트웨어 엔지니어링" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1", text: "Atmospheric chemistry 대기화학" },
        { value:"2", text: "Atmospheric science 대기과학" },
        { value:"3", text: "Climate science 기후과학" },
        { value:"4", text: "Cloud physics 구름물리학" },
        { value:"5", text: "Convective systems, tornadoes, and hurricanes 대류시스템, 토네이도 및 허리케인" },
        { value:"6", text: "Geodesy 측지학" },
        { value:"7", text: "Geology 지질학" },
        { value:"8", text: "Geophysics 지구물리학" },
        { value:"9", text: "Hydrology 수문학" },
        { value:"10",    text: "Meteorology 기상학" },
        { value:"11",    text: "Mineralogy 광물학" },
        { value:"12",    text: "Numerical weather prediction  (기상학의, 일기의) 수치예보" },
        { value:"13",    text: "Oceanography 해양학" },
        { value:"14",    text: "Other - Earth, atmospheric, and planetary science 기타 - 지구과학, 대기과학 및 행성학" },
        { value:"15",    text: "Remote sensing 원격계측탐지" },
        { value:"16",    text: "Seismology and tectonics 지진학과 구조론" },
        { value:"17",    text: "Space and planetary science 공간 및 행성과학" },
        { value:"18",    text: "Synoptic meteorology 종관기상학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1", text: "Agricultural and environmental economics 농업경제학 및 환경경제학" },
        { value:"2", text: "Behavioral economics 행동경제학" },
        { value:"3", text: "Development economics 개발 경제학" },
        { value:"4", text: "Econometrics 계량 (통계) 경제학, 경제 측정학" },
        { value:"5", text: "Economic history 경제사" },
        { value:"6", text: "Economic modeling 경제모형" },
        { value:"7", text: "Economic policy 경제정책" },
        { value:"8", text: "Economic theory 경제이론" },
        { value:"9", text: "Labor economics 노동경제학" },
        { value:"10",    text: "Monetary economics 화폐경제학" },
        { value:"11",    text: "Other - Economics and statistics 기타 - 경제학, 통계학" },
        { value:"12",    text: "Public economics 공공경제학" },
        { value:"13",    text: "Spatial economics 공간경제학" },
        { value:"14",    text: "Statistics in economics and other social sciences 경제통계 및 사회과학" },
        { value:"15",    text: "Tourism economics 관광경제학" },
        { value:"16",    text: "Transport economics 교통경제학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1", text: "Curriculum development 교육과정 개발" },
        { value:"2", text: "Curriculum studies 교육과정 연구" },
        { value:"3", text: "Educational administration 교육관리" },
        { value:"4", text: "Educational assessment and evaluation 교육평가 및 측정" },
        { value:"5", text: "Educational methods and theories 교육방법 및 이론" },
        { value:"6", text: "ELT/TESL/TESOL/TEFL  영어교수학" },
        { value:"7", text: "ESL/EFL/ESOL/EAL  영어교수학" },
        { value:"8", text: "ESP   특수 목적용[직능별] 영어(English for specific/special purposes)" },
        { value:"9", text: "General education 일반교육, 보통교육" },
        { value:"10",    text: "Language acquisition 언어습득" },
        { value:"11",    text: "Language assessment/Language testing 언어평가/언어테스트" },
        { value:"12",    text: "Other - Education 기타 - 교육학" },
        { value:"13",    text: "Pedagogy 교육학" },
        { value:"14",    text: "Specialist studies in education 교육전문연구" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1", text: "Aeronautical engineering 항공공학" },
        { value:"2", text: "Automobile engineering 자동차공학" },
        { value:"3", text: "Biomedical engineering 생명공학" },
        { value:"4", text: "Civil and structural engineering 토목 및 구조공학" },
        { value:"5", text: "Control and systems engineering 제어 및 시스템공학 " },
        { value:"6", text: "Electric circuits and components 전기회로" },
        { value:"7", text: "Electronics and electrical engineering 전기전자공학" },
        { value:"8", text: "Industrial and manufacturing engineering 생산 및 제조공학" },
        { value:"9", text: "Marine engineering 선박공학" },
        { value:"10",    text: "Mechanical engineering 기계공학" },
        { value:"11",    text: "Nanotechnology 나노기술" },
        { value:"12",    text: "Other - Engineering and technology 기타 - 공학 및 기술" },
        { value:"13",    text: "Robotics 로봇공학" },
        { value:"14",    text: "Sensors 센서" },
        { value:"15",    text: "Signal processing 신호분석처리" },
        { value:"16",    text: "Telecommunications 원격통신" },
        { value:"17",    text: "Wireless communication 무선통신" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Energy 에너지" },
        { value:"2",    text: "Environmental policies 환경정책" },
        { value:"3",    text: "Environmental science 환경과학" },
        { value:"4",    text: "Nature and landscape conservation 자연 및 조경 보존" },
        { value:"5",    text: "Other - Environmental science, energy, and sustainability 기타 -  환경에너지과학" },
        { value:"6",    text: "Pollution 공해" },
        { value:"7",    text: "Renewable energy 재생가능에너지" },
        { value:"8",    text: "Sustainability  (생태학 분야) 지속가능성" },
        { value:"9",    text: "Waste management and disposal  폐기물 관리 및 처리" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Archaeology 고고학" },
        { value:"2",    text: "Civics   공민학" },
        { value:"3",    text: "Ethics 윤리학" },
        { value:"4",    text: "Geopolitics 지정학" },
        { value:"5",    text: "History 역사" },
        { value:"6",    text: "History of Africa 아프리카 역사" },
        { value:"7",    text: "History of Asia 아시아 역사" },
        { value:"8",    text: "History of Central Asia 중앙아시아 역사" },
        { value:"9",    text: "History of East Asia 동남아시아 역사" },
        { value:"10",   text: "History of Europe 유럽 역사" },
        { value:"11",   text: "History of the Americas 아메리카 역사" },
        { value:"12",   text: "History of the Middle East 중동 역사" },
        { value:"13",   text: "International relations 국제관계학" },
        { value:"14",   text: "Law 법학" },
        { value:"15",   text: "Other - History, political science, and philosophy 기타 - 역사, 정치학 및 철학" },
        { value:"16",   text: "Philosophy 철학" },
        { value:"17",   text: "Policy planning 정책계획" },
        { value:"18",   text: "Political science 정치학" },
        { value:"19",   text: "Public administration 행정학" },
        { value:"20",   text: "Religious studies and theology 종교학 및 신학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Book reviews 도서리뷰" },
        { value:"2",    text: "Descriptive linguistics 기술언어학" },
        { value:"3",    text: "Fiction and creative writing 소설 및 창작" },
        { value:"4",    text: "General linguistics 일반언어학" },
        { value:"5",    text: "Literary criticism 문학비평, 평론학" },
        { value:"6",    text: "Literary forms and genres 문학양식 및 장르" },
        { value:"7",    text: "Literary history 문학역사" },
        { value:"8",    text: "Literary nonfiction 문학 논픽션" },
        { value:"9",    text: "Literary theory 문학이론" },
        { value:"10",   text: "Literary translation 문학번역" },
        { value:"11",   text: "Literature 문학" },
        { value:"12",   text: "Literature by era 시대문학" },
        { value:"13",   text: "Morphology (언어학)의미론" },
        { value:"14",   text: "National, regional, and ethnic literature 국가, 지역 및 민족문학" },
        { value:"15",   text: "Other - Literature and linguistics 기타 - 문학, 언어학" },
        { value:"16",   text: "Phonology 음성학" },
        { value:"17",   text: "Pragmatics   화용론" },
        { value:"18",   text: "Semantics (언어학)의미론" },
        { value:"19",   text: "Study of creative arts and writing 창작예술 및 쓰기연구" },
        { value:"20",   text: "Syntax (언어)구문론, 통사론" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Ceramics and composites 세라믹 및 복합재료" },
        { value:"2",    text: "Electrode materials 전극재료" },
        { value:"3",    text: "Electronic, optical, and magnetic materials 전자, 광학 및 자성재료" },
        { value:"4",    text: "Fibers and glass 섬유 및 유리" },
        { value:"5",    text: "Material synthesis and processes 소재합성 및 프로세스" },
        { value:"6",    text: "Materials engineering 재료공학" },
        { value:"7",    text: "Materials physics 재료물리학" },
        { value:"8",    text: "Materials science 재료과학" },
        { value:"9",    text: "Metallurgy 금속공학" },
        { value:"10",   text: "Metallurgy, metals, and alloys 야금, 금속 및 합금" },
        { value:"11",   text: "Nanofabrication 나노제작" },
        { value:"12",   text: "Other - Materials science 기타 - 재료과학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Anatomy 해부학" },
        { value:"2",    text: "Anesthesiology and pain medicine 마취통증의학" },
        { value:"3",    text: "Cancer research - Chemoradiotherapy 화학방사선요법" },
        { value:"4",    text: "Cancer research - Molecular 암연구분자" },
        { value:"5",    text: "Cancer research 암연구" },
        { value:"6",    text: "Cardiology 심장(병)학" },
        { value:"7",    text: "Chiropractics 지압요법" },
        { value:"8",    text: "Clinical toxicology 임상 독성학" },
        { value:"9",    text: "Complementary and alternative medicine 보완 및 대체의학" },
        { value:"10",   text: "Dentistry 치과의학" },
        { value:"11",   text: "Dermatology 피부과학" },
        { value:"12",   text: "Diabetes research 당뇨병 연구" },
        { value:"13",   text: "Emergency and critical care 응급의학, 중환자간호" },
        { value:"14",   text: "Endocrinology 내분비학" },
        { value:"15",   text: "ENT (Otolaryngology) 이비인후과 의학" },
        { value:"16",   text: "Epidemiology 유행병학" },
        { value:"17",   text: "Forensic medicine 법의학" },
        { value:"18",   text: "Gastroenterology and hepatology 소화기내과, 간장학(肝臟學)" },
        { value:"19",   text: "Geriatric medicine 노인의학" },
        { value:"20",   text: "Hematology 혈액학" },
        { value:"21",   text: "Infectious diseases 전염병, 감염의학" },
        { value:"22",   text: "Internal medicine 내과(학)" },
        { value:"23",   text: "Medical devices 의료장비" },
        { value:"24",   text: "Nephrology 신장(병)학" },
        { value:"25",   text: "Nursing and hospital medicine 간호학 및 병원의학" },
        { value:"26",   text: "Nutrition and dietetics 영양학" },
        { value:"27",   text: "Obstetrics and gynecology 산부인과" },
        { value:"28",   text: "Occupational health and therapy 산업보건 및 진료" },
        { value:"29",   text: "Ophthalmology 안과학" },
        { value:"30",   text: "Optometry 시력측정" },
        { value:"31",   text: "Orthopedics 정형외과" },
        { value:"32",   text: "Other - Medicine 기타 - 의하" },
        { value:"33",   text: "Pathology and diagnostics 병리학 및 진단학" },
        { value:"34",   text: "Pediatrics, perinatology, and child health 소아과, 출산의료학 및 아동건강" },
        { value:"35",   text: "Physical medicine and rehabilitation 물리 요법학 및 재활의학" },
        { value:"36",   text: "Plastic surgery 성형외과" },
        { value:"37",   text: "Public health 공중위생학" },
        { value:"38",   text: "Radiology 방사선학, 영상의학" },
        { value:"39",   text: "Radiotherapy planning 방사선요법계획" },
        { value:"40",   text: "Reproductive medicine 생식의료" },
        { value:"41",   text: "Respiratory care 호흡관리" },
        { value:"42",   text: "Rheumatology 류머티즘학" },
        { value:"43",   text: "Sexual health 성건강" },
        { value:"44",   text: "Sports medicine 스포츠의학" },
        { value:"45",   text: "Surgery - Cardiac and cardiothoracic 수술 - 심장 및 흉부" },
        { value:"46",   text: "Surgery 외과" },
        { value:"47",   text: "Transplantation - Surgery 이식수술" },
        { value:"48",   text: "Urology 비뇨기과학" },
        { value:"49",   text: "Veterinary sciences (축산학) 수의학(獸醫學)" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Clinical psychiatry 정신의학" },
        { value:"2",    text: "Cognitive neuroscience 인지 신경과학" },
        { value:"3",    text: "Computational neuroscience 계산신경과학" },
        { value:"4",    text: "Developmental neuroscience 발달신경과학" },
        { value:"5",    text: "Neuroanatomy 신경해부학" },
        { value:"6",    text: "Neuroimaging 신경촬영법" },
        { value:"7",    text: "Neuropathology 신경병리학" },
        { value:"8",    text: "Neuroscience and neurology 신경과학 및 신경과" },
        { value:"9",    text: "Neurosurgery 신경외과" },
        { value:"10",   text: "Other - Neuroscience and neurology 기타 - 신경과학, 신경학" },
        { value:"11",   text: "Sensory systems 감각기관" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Drug discovery 신약개발" },
        { value:"2",    text: "Other - Pharmaceutical sciences 약학" },
        { value:"3",    text: "Pharmaceutical chemistry 약제화학" },
        { value:"4",    text: "Pharmacogenomics 약리유전학" },
        { value:"5",    text: "Pharmacognosy 생약학" },
        { value:"6",    text: "Pharmacology, toxicology, and pharmaceutics 약리학, 독성학 및 조제학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Acoustics and ultrasonics 음향 및 초음파" },
        { value:"2",    text: "Applied physics 응용물리학" },
        { value:"3",    text: "Astronomy and astrophysics 천문학 천체물리학" },
        { value:"4",    text: "Atomic and molecular physics 원자물리학, 분자물리학" },
        { value:"5",    text: "Condensed matter physics 응집물질 물리학(고체물리학)" },
        { value:"6",    text: "Fluid dynamics 유체역학" },
        { value:"7",    text: "High-energy and particle physics 고에너지물리학, 소립자물리학" },
        { value:"8",    text: "Lasers 레이져" },
        { value:"9",    text: "Linear physics 선형물리학" },
        { value:"10",   text: "Magnetism 자기, 자성" },
        { value:"11",   text: "Medical physics 의학물리학" },
        { value:"12",   text: "Nonlinear physics 비선형 물리학" },
        { value:"13",   text: "Nuclear physics 핵물리학" },
        { value:"14",   text: "Optics 광학" },
        { value:"15",   text: "Other - Physics 기타 - 물리학" },
        { value:"16",   text: "Plasma 플라즈마" },
        { value:"17",   text: "Quantum physics 양자물리학" },
        { value:"18",   text: "Radiation 방사선" },
        { value:"19",   text: "Solid-state physics 고체물리학" },
        { value:"20",   text: "Statistical and mathematical physics 통계및 수학적 물리학" },
        { value:"21",   text: "Theoretical physics 이론물리학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Agricultural science 농업과학" },
        { value:"2",    text: "Agronomy and crop science 경제학 및 작물과학" },
        { value:"3",    text: "Animal genealogy 동물계통학" },
        { value:"4",    text: "Animal genetics 동물 유전학" },
        { value:"5",    text: "Behavior and systematics 행동 및 분류학" },
        { value:"6",    text: "Botany 식물학" },
        { value:"7",    text: "Ecology 생태학" },
        { value:"8",    text: "Entomology 곤충학" },
        { value:"9",    text: "Fishery sciences 수산업 과학" },
        { value:"10",   text: "Forestry 임학" },
        { value:"11",   text: "Horticulture 원예학" },
        { value:"12",   text: "Irrigation and water management 관개 및 물관리" },
        { value:"13",   text: "Marine Biology 해양생물학" },
        { value:"14",   text: "Ornithology 조류학" },
        { value:"15",   text: "Other - Plant and animal science 기타 - 식물 및 동물과학" },
        { value:"16",   text: "Plant and animal biotechnology 식물 및 동물 생명공학" },
        { value:"17",   text: "Plant biochemistry 식물 생화학" },
        { value:"18",   text: "Plant genealogy 식물계통학" },
        { value:"19",   text: "Plant genetics 식물 유전학" },
        { value:"20",   text: "Soil science 토양학" },
        { value:"21",   text: "Taxonomy 분류학" },
        { value:"22",   text: "Zoology 동물학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Applied behavior analysis 응용행동분석" },
        { value:"2",    text: "Behavioral, psychosomatic, and social medicine 행동, 심리 및 사회의학" },
        { value:"3",    text: "Clinical psychology and mental health 임상정신과" },
        { value:"4",    text: "Clinical psychotherapy and counseling 임상심리학 및 상담학" },
        { value:"5",    text: "Cognitive psychology and affective science 임상심리학, 정서과학" },
        { value:"6",    text: "Comparative psychology 비교심리학" },
        { value:"7",    text: "Developmental and educational psychology 발달심리학 및 산업심리학" },
        { value:"8",    text: "Elder care and gerontology 노인학" },
        { value:"9",    text: "Experimental psychology 실험심리학" },
        { value:"10",   text: "General psychology 일반 심리학" },
        { value:"11",   text: "Health education, management, and informatics 보건교육, 보건관리 및 보건정보학" },
        { value:"12",   text: "Healthcare 건강관리" },
        { value:"13",   text: "Neuropsychology 신경심리학" },
        { value:"14",   text: "Nursing - Policy, support, and development 간호정책, 간호지원 및 간호개발" },
        { value:"15",   text: "Other - Psychology and psychosocial healthcare 기타 - 심리학 및 건강관리" },
        { value:"16",   text: "Social and industrial psychology 사회 및 산업심리학" },
    ], [
        { value:"",  text:'선택 하세요' },
        { value:"1",    text: "Anthropology 인류학" },
        { value:"2",    text: "Consumer behavior and consumer studies 소비자행동 및 소비자학 연구" },
        { value:"3",    text: "Criminology 범죄학" },
        { value:"4",    text: "Cultural studies 문화연구" },
        { value:"5",    text: "Decision sciences 의사결정학" },
        { value:"6",    text: "Demography 인구학" },
        { value:"7",    text: "Disaster management 재해관리" },
        { value:"8",    text: "Gender studies 성 연구" },
        { value:"9",    text: "Geography and environmental studies 지리학 및 환경연구" },
        { value:"10",   text: "Information studies 정보과학" },
        { value:"11",   text: "Organizational behavior 조직행동" },
        { value:"12",   text: "Other - Sociology, anthropology, and organizational behavior 기타 - 사회학, 인류학 및 조직행동학" },
        { value:"13",   text: "Race and ethnicity 인종 및 민족학" },
        { value:"14",   text: "Records management 기록관리" },
        { value:"15",   text: "Rural sociology 농촌사회학" },
        { value:"16",   text: "Social work 사회복지업무" },
        { value:"17",   text: "Sociology 사회학" },
        { value:"18",   text: "Urban sociology 도시사회학" },
    ]

];
export { use_opt, branch_opt, editor_opt };
